name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run SonarCloud Analysis
      uses: sonarsource/sonarcloud-github-action@v3
      with:
        entryPoint: "dotnet"
        args: "sonarscanner begin /k:\"Hforna_WebAPILearningCSharp\" /d:sonar.login=\"${{ secrets.SONAR_TOKEN }}\" /d:sonar.host.url=\"https://sonarcloud.io\""
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: End SonarCloud Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
